"""xfail registry for openCypher TCK tests.

Maps test ID patterns to expected failure reasons and categories.
Uses two tiers: feature-prefix globs (all scenarios fail) and
individual test IDs (partial failures within a feature).

Generated by auditing actual parse results against the Neo4j dialect.

Three TCK test suites share this registry:

  test_tck_parse.py      — Can we parse each query?  (XFAIL_PARSE)
  test_tck_roundtrip.py  — Does parse→generate→re-parse + zero scope diagnostics?  (XFAIL_ROUNDTRIP)
  test_tck_errors.py     — Do invalid queries produce errors?  (XFAIL_ERROR)

Current results (2026-04-01):

  Parse:     3897/3897 = 100%   — 0 xfails
  Roundtrip: 3243/3279 = 99.0%  — 36 xfails (scope validator false positives for Cypher)
  Error:      540/600  = 90.0%  — 60 xfails (need semantic analysis, not syntax)

The 36 roundtrip xfails are NOT parse, generator, or transformation
failures.  They are false positives from the scope/type validator
which applies GQL rules that do not hold for Cypher (e.g., Cypher
allows bound variables in CREATE/MERGE, implicit GROUP BY, etc.).
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from fnmatch import fnmatch


class XFailCategory(Enum):
    """Categories of expected TCK test failures."""

    CYPHER_ONLY = auto()
    """Cypher-specific syntax not supported by GQL parser (e.g., --> arrows)."""
    UNSUPPORTED_FEATURE = auto()
    """Feature not yet implemented (e.g., CALL procedures, pattern comprehensions)."""
    PARSER_BUG = auto()
    """Known parser bug."""
    GENERATOR_BUG = auto()
    """Generator produces incorrect output."""
    SEMANTIC_ONLY = auto()
    """Error requires semantic analysis, not syntactic parsing."""
    LEXER_LIMITATION = auto()
    """Lexer cannot tokenize the input correctly."""
    PARSER_TIMEOUT = auto()
    """Parser hangs on this query (recursion / backtracking)."""


@dataclass(frozen=True)
class XFailEntry:
    """An expected failure entry."""

    reason: str
    category: XFailCategory


# -- Parse xfails (empty — all 3897 TCK scenarios parse successfully) ----------
XFAIL_PARSE: dict[str, XFailEntry] = {}

_INDIVIDUAL_XFAIL_IDS: frozenset[str] = frozenset()


# -- Roundtrip xfails: scope validator false positives for Cypher ---------------
#
# These are NOT transformation or generator bugs.  The scope/type validator
# applies GQL-specific rules that are too strict for Cypher:
#
#   undefined-variable (36) — with_to_next doesn't fire in data-modifying
#                              contexts (DELETE/CREATE after WITH); pattern
#                              comprehension vars not tracked
#
# Total: 36 scenarios (was 62; variable-already-bound resolved by skipping
# check_already_bound for Cypher CREATE/MERGE node bindings; Merge1__8
# remains due to undefined-variable from WITH→MERGE scope loss).
# The WITH...WHERE scope-loss bugs have been fixed; the Delete6__5/12 entries
# remain because with_to_next does not fire in data-modifying contexts.
#
_SCOPE_FP = XFailEntry(
    "Scope validator false positive for Cypher semantics",
    XFailCategory.SEMANTIC_ONLY,
)
XFAIL_ROUNDTRIP: dict[str, XFailEntry] = {
    # -- undefined-variable: WITH→MERGE scope loss (with_to_next in data-modifying) --
    "Merge1__8_Merge_should_handle_argument_properly": _SCOPE_FP,
    # -- undefined-variable: WITH in data-modifying context / pattern comprehension --
    "Delete5__1_Delete_node_from_a_list": _SCOPE_FP,
    "Delete5__2_Delete_relationship_from_a_list": _SCOPE_FP,
    "Delete5__3_Delete_nodes_from_a_map": _SCOPE_FP,
    "Delete5__4_Delete_relationships_from_a_map": _SCOPE_FP,
    "Delete5__5_Detach_delete_nodes_from_nested_map_list": _SCOPE_FP,
    "Delete5__6_Delete_relationships_from_nested_map_list": _SCOPE_FP,
    "Delete5__7_Delete_paths_from_nested_map_list": _SCOPE_FP,
    "Delete6__6_Aggregating_in_RETURN_after_deleting_nodes_affects_the_resul": _SCOPE_FP,
    "Delete6__7_Aggregating_in_WITH_after_deleting_nodes_affects_the_result": _SCOPE_FP,
    "Delete6__5_Filtering_after_deleting_nodes_affects_the_result_set_but_no": _SCOPE_FP,
    "Delete6__12_Filtering_after_deleting_relationships_affects_the_result_se": _SCOPE_FP,
    "Delete6__13_Aggregating_in_RETURN_after_deleting_relationships_affects_t": _SCOPE_FP,
    "Delete6__14_Aggregating_in_WITH_after_deleting_relationships_affects_the": _SCOPE_FP,
    "Pattern2__1_Return_a_pattern_comprehension": _SCOPE_FP,
    "Pattern2__2_Return_a_pattern_comprehension_with_label_predicate": _SCOPE_FP,
    "Pattern2__3_Return_a_pattern_comprehension_with_bound_nodes": _SCOPE_FP,
    "Pattern2__4_Introduce_a_new_node_variable_in_pattern_comprehension": _SCOPE_FP,
    "Pattern2__5_Introduce_a_new_relationship_variable_in_pattern_comprehensi": _SCOPE_FP,
    "Pattern2__6_Aggregate_on_a_pattern_comprehension": _SCOPE_FP,
    "Pattern2__8_Use_a_pattern_comprehension_in_WITH": _SCOPE_FP,
    "Pattern2__9_Use_a_variable_length_pattern_comprehension_in_WITH": _SCOPE_FP,
    "Pattern2__10_Use_a_pattern_comprehension_in_RETURN": _SCOPE_FP,
    "Pattern2__11_Use_a_pattern_comprehension_and_ORDER_BY": _SCOPE_FP,
    "ExistentialSubquery1__4_Simple_subquery_with_WHERE_clause_not_existing_pattern": _SCOPE_FP,
    "Path1__1_nodes_on_null_path": _SCOPE_FP,
    "Path2__3_relationships_on_null_path": _SCOPE_FP,
    "Unwind1__6_Creating_nodes_from_an_unwound_parameter_list": _SCOPE_FP,
    # -- undefined-variable: list comprehension scope / data-modifying context --
    "List12__1_Collect_and_extract_using_a_list_comprehension": _SCOPE_FP,
    "List12__2_Collect_and_filter_using_a_list_comprehension": _SCOPE_FP,
    "Set6__7_Aggregating_in_WITH_after_setting_a_property_on_nodes_affect": _SCOPE_FP,
    "Set6__14_Aggregating_in_WITH_after_adding_a_label_on_nodes_affects_th": _SCOPE_FP,
    "Set6__21_Aggregating_in_WITH_after_setting_a_property_on_relationship": _SCOPE_FP,
    "Remove3__7_Aggregating_in_WITH_after_removing_a_property_from_nodes_aff": _SCOPE_FP,
    "Remove3__14_Aggregating_in_WITH_after_removing_a_label_from_nodes_affect": _SCOPE_FP,
    "Remove3__21_Aggregating_in_WITH_after_removing_a_property_from_relations": _SCOPE_FP,
}

XFAIL_ERROR: dict[str, XFailEntry] = {}


def should_xfail_parse(test_id: str, query: str) -> XFailEntry | None:
    """Check if a parse test should be xfailed.

    First checks the static glob registry, then individual test IDs.
    The query parameter is accepted for API compatibility but no longer
    used for runtime regex classification.
    """
    # Static registry (exact + glob)
    entry = get_xfail(test_id, XFAIL_PARSE)
    if entry:
        return entry

    # Individual test IDs
    if test_id in _INDIVIDUAL_XFAIL_IDS:
        return XFailEntry(
            "Cypher syntax partially unsupported in this context", XFailCategory.UNSUPPORTED_FEATURE
        )

    return None


def get_xfail(test_id: str, registry: dict[str, XFailEntry]) -> XFailEntry | None:
    """Look up an xfail entry for a test ID.

    Checks exact match first, then glob patterns.
    """
    if test_id in registry:
        return registry[test_id]
    for pattern, entry in registry.items():
        if "*" in pattern or "?" in pattern:
            if fnmatch(test_id, pattern):
                return entry
    return None
