"""xfail registry for openCypher TCK tests.

Maps test ID patterns to expected failure reasons and categories.
Uses two tiers: feature-prefix globs (all scenarios fail) and
individual test IDs (partial failures within a feature).

Generated by auditing actual parse results against the Neo4j dialect.

Three TCK test suites share this registry:

  test_tck_parse.py      — Can we parse each query?  (XFAIL_PARSE)
  test_tck_roundtrip.py  — Does parse→generate→re-parse + zero scope diagnostics?  (XFAIL_ROUNDTRIP)
  test_tck_errors.py     — Do invalid queries produce errors?  (XFAIL_ERROR)

Current results (2026-04-02):

  Parse:     3897/3897 = 100%   — 0 xfails
  Roundtrip: 3279/3279 = 100%   — 0 xfails
  Error:      540/600  = 90.0%  — 60 xfails (need semantic analysis, not syntax)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from fnmatch import fnmatch


class XFailCategory(Enum):
    """Categories of expected TCK test failures."""

    CYPHER_ONLY = auto()
    """Cypher-specific syntax not supported by GQL parser (e.g., --> arrows)."""
    UNSUPPORTED_FEATURE = auto()
    """Feature not yet implemented (e.g., CALL procedures, pattern comprehensions)."""
    PARSER_BUG = auto()
    """Known parser bug."""
    GENERATOR_BUG = auto()
    """Generator produces incorrect output."""
    SEMANTIC_ONLY = auto()
    """Error requires semantic analysis, not syntactic parsing."""
    LEXER_LIMITATION = auto()
    """Lexer cannot tokenize the input correctly."""
    PARSER_TIMEOUT = auto()
    """Parser hangs on this query (recursion / backtracking)."""


@dataclass(frozen=True)
class XFailEntry:
    """An expected failure entry."""

    reason: str
    category: XFailCategory


# -- Parse xfails (empty — all 3897 TCK scenarios parse successfully) ----------
XFAIL_PARSE: dict[str, XFailEntry] = {}

_INDIVIDUAL_XFAIL_IDS: frozenset[str] = frozenset()


# -- Roundtrip xfails (empty — all 3279 scenarios round-trip successfully) -----
XFAIL_ROUNDTRIP: dict[str, XFailEntry] = {}

XFAIL_ERROR: dict[str, XFailEntry] = {}

# -- Inverse-transform xfails (cypher → with_to_next → GQL → next_to_with → cypher) -
#
# Categorized so future improvements can pick off entries one bucket at a time.
XFAIL_INVERSE: dict[str, XFailEntry] = {
    # WITH * (no WHERE) over an empty scope is silently dropped by with_to_next
    # (transformations.py:_segments_introduce_bindings); the marker `RETURN *`
    # would otherwise fail scope validation.  Inverse can't recover the
    # original WITH *.
    "Create3__2_WITH_CREATE": XFailEntry(
        "WITH * over empty scope silently dropped — see transformations.py "
        "_segments_introduce_bindings",
        XFailCategory.UNSUPPORTED_FEATURE,
    ),
    "Create3__3_MATCH_CREATE_WITH_CREATE": XFailEntry(
        "WITH * over empty scope silently dropped — see transformations.py "
        "_segments_introduce_bindings",
        XFailCategory.UNSUPPORTED_FEATURE,
    ),
    # WHERE mixes the alias (`name`) and the source expression (`a.name2`) for
    # the same binding.  with_to_next's `_inline_aliases` is many-to-one here:
    # both forms collapse to `a.name2`, and no inverse can recover which
    # occurrence was originally the alias.  Semantically equivalent on both
    # sides, but strict AST equality fails.
    "WithWhere7__3_WHERE_sees_both_variable_bound_before_but_not_after_WITH_and": XFailEntry(
        "Mixed alias/source reference in WHERE — alias inlining is many-to-one "
        "(semantics preserved, AST shape lost)",
        XFailCategory.UNSUPPORTED_FEATURE,
    ),
    # 40-level nested map literal hits CPython recursion limit inside with_to_next's
    # tree walk.  Same root cause as test_tck_roundtrip.py's `_SKIP_SCOPE_IDS` list.
    "Literals8__16_Return_40_deep_nested_maps": XFailEntry(
        "Deep nested AST exceeds CPython recursion limit during transform",
        XFailCategory.PARSER_TIMEOUT,
    ),
}


def should_xfail_parse(test_id: str, query: str) -> XFailEntry | None:
    """Check if a parse test should be xfailed.

    First checks the static glob registry, then individual test IDs.
    The query parameter is accepted for API compatibility but no longer
    used for runtime regex classification.
    """
    # Static registry (exact + glob)
    entry = get_xfail(test_id, XFAIL_PARSE)
    if entry:
        return entry

    # Individual test IDs
    if test_id in _INDIVIDUAL_XFAIL_IDS:
        return XFailEntry(
            "Cypher syntax partially unsupported in this context", XFailCategory.UNSUPPORTED_FEATURE
        )

    return None


def get_xfail(test_id: str, registry: dict[str, XFailEntry]) -> XFailEntry | None:
    """Look up an xfail entry for a test ID.

    Checks exact match first, then glob patterns.
    """
    if test_id in registry:
        return registry[test_id]
    for pattern, entry in registry.items():
        if "*" in pattern or "?" in pattern:
            if fnmatch(test_id, pattern):
                return entry
    return None
