"""xfail registry for openCypher TCK tests.

Maps test ID patterns to expected failure reasons and categories.
Uses two tiers: feature-prefix globs (all scenarios fail) and
individual test IDs (partial failures within a feature).

Generated by auditing actual parse results against the Neo4j dialect.

Three TCK test suites share this registry:

  test_tck_parse.py      — Can we parse each query?  (XFAIL_PARSE)
  test_tck_roundtrip.py  — Does parse→generate→re-parse + zero scope diagnostics?  (XFAIL_ROUNDTRIP)
  test_tck_errors.py     — Do invalid queries produce errors?  (XFAIL_ERROR)

Current results (2026-04-02):

  Parse:     3897/3897 = 100%   — 0 xfails
  Roundtrip: 3279/3279 = 100%   — 0 xfails
  Error:      540/600  = 90.0%  — 60 xfails (need semantic analysis, not syntax)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto
from fnmatch import fnmatch


class XFailCategory(Enum):
    """Categories of expected TCK test failures."""

    CYPHER_ONLY = auto()
    """Cypher-specific syntax not supported by GQL parser (e.g., --> arrows)."""
    UNSUPPORTED_FEATURE = auto()
    """Feature not yet implemented (e.g., CALL procedures, pattern comprehensions)."""
    PARSER_BUG = auto()
    """Known parser bug."""
    GENERATOR_BUG = auto()
    """Generator produces incorrect output."""
    SEMANTIC_ONLY = auto()
    """Error requires semantic analysis, not syntactic parsing."""
    LEXER_LIMITATION = auto()
    """Lexer cannot tokenize the input correctly."""
    PARSER_TIMEOUT = auto()
    """Parser hangs on this query (recursion / backtracking)."""


@dataclass(frozen=True)
class XFailEntry:
    """An expected failure entry."""

    reason: str
    category: XFailCategory


# -- Parse xfails (empty — all 3897 TCK scenarios parse successfully) ----------
XFAIL_PARSE: dict[str, XFailEntry] = {}

_INDIVIDUAL_XFAIL_IDS: frozenset[str] = frozenset()


# -- Roundtrip xfails (empty — all 3279 scenarios round-trip successfully) -----
XFAIL_ROUNDTRIP: dict[str, XFailEntry] = {}

XFAIL_ERROR: dict[str, XFailEntry] = {}


def should_xfail_parse(test_id: str, query: str) -> XFailEntry | None:
    """Check if a parse test should be xfailed.

    First checks the static glob registry, then individual test IDs.
    The query parameter is accepted for API compatibility but no longer
    used for runtime regex classification.
    """
    # Static registry (exact + glob)
    entry = get_xfail(test_id, XFAIL_PARSE)
    if entry:
        return entry

    # Individual test IDs
    if test_id in _INDIVIDUAL_XFAIL_IDS:
        return XFailEntry(
            "Cypher syntax partially unsupported in this context", XFailCategory.UNSUPPORTED_FEATURE
        )

    return None


def get_xfail(test_id: str, registry: dict[str, XFailEntry]) -> XFailEntry | None:
    """Look up an xfail entry for a test ID.

    Checks exact match first, then glob patterns.
    """
    if test_id in registry:
        return registry[test_id]
    for pattern, entry in registry.items():
        if "*" in pattern or "?" in pattern:
            if fnmatch(test_id, pattern):
                return entry
    return None
